version: '3.9'
services:
  app:
    image: my-app-image:latest
    build:
      context: .
    #ports:
     # - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: wp
      POSTGRES_PASSWORD: wp123
      POSTGRES_DB: e-shop
    ports:
      - "5432:5432"
